function figures = CrossectionFigures
figures=JournalFigureStub.empty;

prestretch = 2.5;
cellLengthAtPretretch = 50e-3;
spacing = 0.0600*2.5;
nCells = 3;

thread = Thread.ConstructThreadWithSpacedElectrodes( ...
                prestretch, ...
                cellLengthAtPretretch, ...
                nCells, ...
                spacing, ...
                LocalAlwaysOffModel, ...
                ExternalAlwaysOffModel, ...
                GentParams.Koh2012);

 figures(end+1) = CrossectionFigure(thread, 'systemCrossSectionUnactuated', 'd_{1}\lambda_{pre,1}', 'd_{2}\lambda_{pre,1}');
 
 
 thread = Thread.ConstructThreadWithSpacedElectrodes( ...
                prestretch, ...
                cellLengthAtPretretch, ...
                nCells, ...
                spacing, ...
                LocalAlwaysOffModel, ...
                ExternalAlwaysOffModel, ...
                GentParams.Koh2012);
            
for element = thread.Elements
    if(element.IsElectroded)
        element.SetStretchRatio(5);
    else
        element.SetStretchRatio(1.25);
    end
end
figures(end+1) = CrossectionFigure(thread, 'systemCrossSectionActuated', 'd_{1}\lambda_{C}', 'd_{2}\lambda_{P}');  

end